### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by sonjasil** [HeljaeRaeisaenen/keskustelupasta#1]
Sovellus lähti hyvin käyntiin käynnistysohjeilla, ja sitä on miellyttävä käyttää. Sivun ulkoasu näyttää hyvältä. Itse koodi näyttää olevan hyvin jaoiteltu osiin tiedostoissa. Kun käyttäjä yrittää kirjautua sisään väärällä tunnuksella tai salasanalla, tulee virheilmoitus "Virhe: Väärä käyttäjätunnus tai salasana". Sama ilmoitus tulee myös jos yrittää kirjautua poistetulle tilille. Itse käyttäjänä pitäisin selkeämpänä, jos salasanavirhe ja olematon käyttäjänimi -virhe olisivat erilliset, mutta tämä on ehkä enemmän mielipideasia. Sovellus kokonaisuutena toimii hyvin.

**Comment by HeljaeRaeisaenen** [comment]
Kiitos arvioinnista!
